--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: timescaledb; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS timescaledb WITH SCHEMA public;


--
-- Name: EXTENSION timescaledb; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION timescaledb IS 'Enables scalable inserts and complex queries for time-series data (Community Edition)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ip_enabled_histories; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.ip_enabled_histories (
    id integer NOT NULL,
    ip_id integer NOT NULL,
    enabled boolean NOT NULL,
    changed_at timestamp with time zone NOT NULL
);


ALTER TABLE public.ip_enabled_histories OWNER TO "user";

--
-- Name: ip_enabled_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.ip_enabled_histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ip_enabled_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ips; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.ips (
    id integer NOT NULL,
    ip_address inet NOT NULL,
    enabled boolean DEFAULT true NOT NULL
);


ALTER TABLE public.ips OWNER TO "user";

--
-- Name: ips_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.ips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pings; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.pings (
    ip_id integer NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    rtt numeric,
    packet_loss boolean DEFAULT false NOT NULL
);


ALTER TABLE public.pings OWNER TO "user";

--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


ALTER TABLE public.schema_migrations OWNER TO "user";

--
-- Name: ip_enabled_histories ip_enabled_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.ip_enabled_histories
    ADD CONSTRAINT ip_enabled_histories_pkey PRIMARY KEY (id);


--
-- Name: ips ips_ip_address_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.ips
    ADD CONSTRAINT ips_ip_address_key UNIQUE (ip_address);


--
-- Name: ips ips_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.ips
    ADD CONSTRAINT ips_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: pings_ip_id_timestamp_index; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX pings_ip_id_timestamp_index ON public.pings USING btree (ip_id, "timestamp");


--
-- Name: pings_timestamp_idx; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX pings_timestamp_idx ON public.pings USING btree ("timestamp" DESC);


--
-- Name: pings ts_insert_blocker; Type: TRIGGER; Schema: public; Owner: user
--

CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.pings FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker();


--
-- Name: ip_enabled_histories ip_enabled_histories_ip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.ip_enabled_histories
    ADD CONSTRAINT ip_enabled_histories_ip_id_fkey FOREIGN KEY (ip_id) REFERENCES public.ips(id) ON DELETE CASCADE;


--
-- Name: pings pings_ip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.pings
    ADD CONSTRAINT pings_ip_id_fkey FOREIGN KEY (ip_id) REFERENCES public.ips(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

